w3c/wai-statements

index.md

To quickly and directly show readers *what* an accessibility statement is!

Examples up top - with comprehensive collapsed

---

content-images/wai-statements/statements.css
index.html
index.md

Hi,
Updates for:
- Minor label / legend styling
- Standard applied fieldset (WCAG20 AA WCAG 2.1 AA, Other)
- Preview button smaller

Updates wai statement generator

---

index.html

Update index; Add button-small class to info-open buttons

---

content-images/wai-statements/statements.css
content-images/wai-statements/statements.js
generator.html

reading from ltr to reading from up to down

Limitations conversion from table to set of fieldsets

---

content-images/wai-statements/statements.css
content-images/wai-statements/statements.js
example-statement1.html
example-statement2.html
example-statement3.html
generator.html

All 3 made by Leon statement examples

Add statement examples

---

generator.html

Fixes inconsistent whitespace at the "Standards applied" group

Update Generator grouping; Apply consistent grouping "Basic Information"

---

content-images/wai-statements/statements.css
content-images/wai-statements/statements.js
generator.html

**FYI**: Mayor script overhaul to make it easier to add new / remove old data and make developr's life easier. Dont scare, output must / will be the same.
And adressed issue #42 and made sure the preview output is what we want it to be.

GH-42; Indicate missing text

---

content-images/wai-statements/statements.js

Getting a value from a htmlcollection does not work for IE Edge

HOTFIX; Rewrite getting values from input groups

---

content-images/wai-statements/statements.js
generator.html

Updated conditional functionality to check for multiple formdata set.
Updated preview template accordingly.

Reflect minimal statement

---

content-images/wai-statements/statements.js
generator.html

Added microformatted markup.
Some fixes for cleaning generated Statement

Add microformatted classnames to statement preview

---

content-images/wai-statements/statements.js
generator.html

Filters to capitalize or lowercase strings in statement preview

GH-39 Add print filters

---

complete-example.html
generator.html
minimal-example.html

Updated.
This is actual html otput from download button. (Microformatted and clean html)

GH-40 Redo example statements

---

content-images/wai-statements/statements.js

Try and make downloads work for IE and EDGE

ie and edge have different download approach

---

generator.html

Fixing styling (GH-63) and typo (GH-64)

Hotfixes for GH-63 and GH-64

---

generator.html

In reply to #70 :
- Add conditions to contact options and response time (require data)
- Add conditions to full Feedback section (require any contact option data)
Condition meaning to display section if met (data set by generator form).

GH-70; Preview: dont display feedback if no contact is filled

---

generator.html

GH-73: Technologies used; Remove declared lines

---

content-images/wai-statements/generator.js
generator.html

Change date input to text type for user controlled output in preview

---

generator.html

For #76;
Feel free to change (link) text / href value.

GH-76; Add link back to statement generator in preview

---

generator.html

I don't think this is a big deal, so feel free to not do it.
Ref: https://github.com/w3c/wai-statements/issues/82

[ED] guidance on date

---

complete-example.html
generator.html
minimal-example.html

GH-74; Change work days into business days

---

complete-example.html

per https://github.com/w3c/wai-statements/issues/82 & https://github.com/w3c/wai-statements/pull/92

write out month

---

README.md

Minor corrections to the usage of English

English language updates

---

index.html

On intro page, add link to the WAI Website Accessibility Statement as an example

---

generator.html

Add new "Date" heading level 3

---

generator.html

No text was changed, it was just moved.
Closes #109

Switch order of the "Approval" and "Complaints" sections

---

generator.html

Delete boilerplate sentences about the organization's positions and actions (in the generated statement)

---

generator.html

Change one word: "targets" to "goals"

---

generator.html

Replace example "live captioning" to "context-sensitive help"

---

content/acknowledgements.md
content/changelog.md
content/complete-example.html
content/generator.md
content/index.html
content/minimal-example.html

⚠️ Merge after https://github.com/w3c/wai-website-data/pull/170 & https://github.com/w3c/wai-website-theme/pull/107

Update last_updated dates
